name: Run tests

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        run: npm ci

      - name: Test and push
        run: |
          if npm test; then
            echo "Passed!"
          else
            echo "Failed!"
            exit 1
          fi
